include_guard(GLOBAL)

function(lucaria_find_xplatform_android)
    set(_ndk_candidates)
    if(DEFINED ENV{ANDROID_NDK_ROOT})
        list(APPEND _ndk_candidates "$ENV{ANDROID_NDK_ROOT}")
    endif()
    if(DEFINED ENV{ANDROID_NDK_HOME})
        list(APPEND _ndk_candidates "$ENV{ANDROID_NDK_HOME}")
    endif()
    if(DEFINED ENV{ANDROID_NDK_DIR})
        list(APPEND _ndk_candidates "$ENV{ANDROID_NDK_DIR}")
    endif()
    if(DEFINED ENV{ANDROID_SDK_ROOT})
        file(GLOB _ndk_dirs "$ENV{ANDROID_SDK_ROOT}/ndk/*")
        list(APPEND _ndk_candidates ${_ndk_dirs})
    endif()
    set(_is_ndk_found FALSE)
    foreach(_candidate IN LISTS _ndk_candidates)
        if(EXISTS "${_candidate}/build/cmake/android.toolchain.cmake")
            set(_ndk_dir "${_candidate}")
            set(_is_ndk_found TRUE)
            break()
        endif()
    endforeach()
    if(NOT _is_ndk_found)
        find_program(_ndkbuild_executable ndk-build)
        if(_ndkbuild_executable)
            get_filename_component(_ndk_dir "${_ndkbuild_executable}" DIRECTORY)
            get_filename_component(_ndk_root "${_ndk_dir}/.." ABSOLUTE)
            if(EXISTS "${_ndk_root}/build/cmake/android.toolchain.cmake")
                set(_ndk_dir "${_ndk_root}")
                set(_is_ndk_found TRUE)
            endif()
        endif()
    endif()
    if(_is_ndk_found)
		set(lucaria_xplatform_android_toolchain "${_ndk_dir}/build/cmake/android.toolchain.cmake" CACHE PATH "Android toolchain file")
		message(STATUS "Found xplatform [Android] SDKs at ${_ndk_dir}")
		if(WIN32)
			set(lucaria_xplatform_android_gradlew "gradlew.bat" CACHE PATH "Android gradlew")
		else()
			set(lucaria_xplatform_android_gradlew "gradlew" CACHE PATH "Android gradlew")
		endif()
    endif()
endfunction()