include_guard(GLOBAL)

function(add_lucaria_game TARGET)
    if(DEFINED LUCARIA_TARGET)
        message(FATAL_ERROR "add_lucaria_game() was already called")
    endif()
    set(options)
    set(one_value_args)
    set(multi_value_args SOURCES INCLUDE_DIRS DEFINES BUILD_ARGS)
    cmake_parse_arguments(PARSE_ARGV 1 LBG "${options}" "${one_value_args}" "${multi_value_args}")
    if(NOT TARGET)
        message(FATAL_ERROR "add_lucaria_game requires a target/output name")
    endif()
    if(NOT LBG_SOURCES)
        message(FATAL_ERROR "add_lucaria_game(${TARGET}) requires SOURCES")
    endif()
    set(LUCARIA_TARGET "${TARGET}" PARENT_SCOPE)
    set(LUCARIA_USER_TARGET user_game PARENT_SCOPE)
    set(LUCARIA_TARGET_SOURCES "${LBG_SOURCES}" PARENT_SCOPE)
    set(LUCARIA_TARGET_INCLUDE_DIRS "${LBG_INCLUDE_DIRS}" PARENT_SCOPE)
    set(LUCARIA_TARGET_DEFINES "${LBG_DEFINES}" PARENT_SCOPE)
    set(LUCARIA_TARGET_BUILD_ARGS "${LBG_BUILD_ARGS}" PARENT_SCOPE)
endfunction()