include_guard(GLOBAL)

include("${CMAKE_CURRENT_LIST_DIR}/find_xplatform_android.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/find_xplatform_psp.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/find_xplatform_web.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/make_configure.cmake")

function(add_lucaria_superbuild GAME_DIR)
    get_filename_component(GAME_DIR "${GAME_DIR}" ABSOLUTE)
    set(options)
    set(one_value_args BINARY_DIR)
    set(multi_value_args PLATFORMS)
    cmake_parse_arguments(PARSE_ARGV 1 LSB "${options}" "${one_value_args}" "${multi_value_args}")
    if(NOT EXISTS "${GAME_DIR}/build.cmake")
        message(FATAL_ERROR "Missing Lucaria game script: ${GAME_DIR}/build.cmake")
    endif()
    if(NOT LSB_BINARY_DIR)
        set(LSB_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}/lucaria")
    endif()
    lucaria_find_xplatform_android()
    lucaria_find_xplatform_psp()
    lucaria_find_xplatform_web()
    if(NOT LSB_PLATFORMS)
        set(LSB_PLATFORMS)
        if(WIN32)
            list(APPEND LSB_PLATFORMS win32)
        endif()
        if(lucaria_xplatform_android_toolchain)
            list(APPEND LSB_PLATFORMS android)
        endif()
        if(lucaria_xplatform_web_toolchain)
            list(APPEND LSB_PLATFORMS web)
        endif()
        if(lucaria_xplatform_psp_cmake_executable)
            list(APPEND LSB_PLATFORMS psp)
        endif()
    endif()
    foreach(platform IN LISTS LSB_PLATFORMS)
        lucaria_make_configure(
            PLATFORM "${platform}"
            GAME_DIR "${GAME_DIR}"
            GAME_BINARY_DIR "${LSB_BINARY_DIR}/${platform}")
    endforeach()
endfunction()