include_guard(GLOBAL)

function(_lucaria_find_xplatform_web)
    if(DEFINED ENV{EMSDK})
        set(_emsdk_dir "$ENV{EMSDK}")
    elseif(DEFINED ENV{EMSCRIPTEN})
        set(_emsdk_dir "$ENV{EMSCRIPTEN}")
    endif()
    if(_emsdk_dir AND EXISTS "${_emsdk_dir}")
        set(_is_emsdk_found TRUE)
    else()
        find_program(_emcc_executable NAMES emcc PATHS ENV PATH)
        if(_emcc_executable)
            get_filename_component(_emsdk_dir_relative "${_emcc_executable}" DIRECTORY)
            get_filename_component(_emsdk_dir "${_emsdk_dir_relative}/../../" ABSOLUTE)
            if(EXISTS "${_emsdk_dir}")
                set(_is_emsdk_found TRUE)
            endif()
        endif()
    endif()
    set(_toolchain "${_emsdk_dir}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake")
    if(_is_emsdk_found AND EXISTS "${_toolchain}")
        message(STATUS "Found xplatform [Web] SDKs at ${_emsdk_dir}")
        set(lucaria_xplatform_web_toolchain "${_toolchain}" CACHE PATH "Web toolchain file")
    endif()
endfunction()